# Generated by Django 4.2.7 on 2023-11-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=100, null=True)),
                ('species_url', models.URLField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('original_title', models.CharField(max_length=200)),
                ('original_title_romanised', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('movie_banner', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=4)),
                ('running_time', models.CharField(max_length=50)),
                ('rt_score', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.URLField(max_length=500)),
                ('actors', models.ManyToManyField(to='movies.actor')),
            ],
        ),
    ]
